### ISSUE TITLE
Error in running genetic diversity diffs 

### ISSUE THREAD

**Issue by Aljumiliy1** [laninsky/genetic_diversity_diffs#1]
Dear Alana,
I am trying to run your script on my sequence data, I have short fragment (397 bp) of haploid sequence samples. It runs well at the beginning until I get an error message, please see a copy of my screen below:

 [1] STEP ONE: Loading in all the variables
[1] 
[1] An error message after this indicates your working directory is not valid
[1] Not to worry, your working directory IS valid! I've successfully set the working directory
[1] 
[1] An error message after this indicates your file is not located in the directory you listed
[1] Not to worry, your file IS located in the directory! I'm pulling it into my memory to extract the parts we are interested in
[1] 
[1] I have found the haplotype definition block in your arlequin file
Error in if (minhaplength == maxhaplength) { : 
  missing value where TRUE/FALSE needed

The script I have used is :
genetic_diversity_diffs("C:/Users/mbx/Desktop/pvalue","samples.arp",1000,"Y","Y")

My data file has been modified to meet the same criteria for the example file that found with the script, I have uploaded a text data file similar to the .arp one I have used.

kindest regards,

Ahmed

[samples.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3132191/samples.txt)

**Comment by laninsky** [comment]
Hi Ahmed,

Thanks for taking the time to log this issue. The bug happened because the code was not expecting any blank lines within the haplotype definition block, but you had an empty line between `HaplList ={ ` and  `Hap_1   TCTTGTATCATCATCAATCCAT`. I've tweaked the code so that it will now deal with files formatted like that, so hopefully it will be good to go for you if you reclone the repository. I've also attached the output files from running your input file on my computer just in case you want to double check the code is running correctly for you.

Sorry for the inconvenience!

Alana

[nucl_diffs_summary.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3133297/nucl_diffs_summary.txt)
[nucleotide_diversity_differences.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3133298/nucleotide_diversity_differences.txt)
[hapl_diffs_summary.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3133299/hapl_diffs_summary.txt)
[haplist.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3133300/haplist.txt)
[haplotype_diversity_differences.txt](https://github.com/laninsky/genetic_diversity_diffs/files/3133301/haplotype_diversity_differences.txt)

**Comment by Aljumiliy1** [comment]
Thank you Alana, everything going smoothly now.
Ahmed

**Comment by laninsky** [comment]
Awesome, glad to hear it Ahmed - let me know if you run into any other bugs!
